openapi: 3.0.3
info:
  title: BAPS Chatbot Copilot Plugin
  description: Plugin to fetch personal user data from BAPS backend
  version: 'v1'
servers:
  - url: https://bapsai.com:1443/bapsChatbotSfBackendDev-0.0.1-SNAPSHOT
paths:
  /baps/get/getPublicProfile:
    get:
      operationId: getPublicProfile
      summary: Get public profile
      description: Fetches public profile using userId
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
        - name: api-key
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response with personal data
          content:
            application/json:
              schema:
                type: object
                properties:
                  firstName:
                    type: string
                  lastName:
                    type: string
                  email:
                    type: string
                  jobTitle:
                    type: string
        '401':
          description: Unauthorized - API key missing or invalid
        '500':
          description: Server error
components: {}
