openapi: 3.0.3
info:
  title: BAPS Chatbot Plugin
  description: Plugin to fetch profile data using email (with consent)
  version: 'v1'
servers:
  - url: https://bapsai.com:1443/bapsChatbotSfBackendDev-0.0.1-SNAPSHOT
paths:
  /baps/get/getPublicProfile:
    get:
      operationId: getPublicProfile
      summary: Get profile by email
      description: Fetch profile information using user’s email address (only with consent)
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
        - name: api-key
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response with profile data
          content:
            application/json:
              schema:
                type: object
                properties:
                  firstName:
                    type: string
                  lastName:
                    type: string
                  email:
                    type: string
                  jobTitle:
                    type: string
        '401':
          description: Unauthorized
        '500':
          description: Server error
